### ISSUE TITLE
Move email to archive, rather than copy?

### ISSUE THREAD

**Issue by robhester** [Matsuo3rd/mac-mail-archiver#1]
This is awesome, thank you for sharing! 

If I wanted to create a version that **moved**, rather than copied, the email would you have a suggestion on tweaks? I am sorry for lack of scripting knowledge, here. Perhaps something like:
`"set mailbox of theMessage to mailbox "Archive""`

Any guidance would be greatly appreciated!

**Comment by Matsuo3rd** [comment]
The script actually moves emails. Do you have a different experience?
See script line 66:
`move messageToArchive to mailbox targetMailbox`

**Comment by robhester** [comment]
You're completely right. Nothing to change here. Thanks!
